data_augmentation:
    shear_range: 0.1
    zoom_range: 0.2
    horizontal_flip: True
    rotation_range: 10
    brightness_range: [0.7, 1.3]

dataset: 'cartoonset10k'
image_shape: [124, 124, 3]
train_split: 0.9
classes: ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11']
batch_balance: [4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 20]
val_batch_size: 64


lr: 0.001
loss: 'categorical_crossentropy'

epochs: 5

save_dir: 'v1'
train_from_scratch: True
load_model_filename: ''

random_seed: 586
shuffle: True
